### ISSUE TITLE
Incompatible with Fan Translation

### ISSUE THREAD

**Issue by romh-acking** [abekermsx/Final-Fantasy-MSX-Performance-Patch#1]
The fan translation is conflicting with the performance patch as it repacks and expands a few files. The game runs normally, however, it messes with progression flags and garland won't be present at the beginning of the game.

Would it be possible to make your patcher aware of what sectors the files are situated in the disk image? The disk image format has a table for the file's names and the start and end sectors that you can reference.

**Comment by abekermsx** [comment]
I updated the code so you can patch the individual files and sectors.
