### ISSUE TITLE
[Question] Extracting the translations in plain text

### ISSUE THREAD

**Issue by alvations** [abekermsx/Final-Fantasy-MSX-Performance-Patch#2]
Thank you for the work in the MSX patch!

Pardon the noob question, is it possible to extract a plain text file of the original Japanese texts and the English translations from the various ASM or BPS file?

**Comment by abekermsx** [comment]
Thanks!

I just created the performance patch, not the patch for the translation. But I've taken a look at the translation patch. If you download the repository from https://github.com/romh-acking/final-fantasy-msx2-en you can find all the Japanese and English texts in script/Script.json. (Don't run the Dump.bat command, it'll overwrite Script.json, removing the English texts)

**Comment by alvations** [comment]
Thanks for the note to the script/Script.json! And again for the patch too =)
