### ISSUE TITLE
[Question] Modify playable characters names

### ISSUE THREAD

**Issue by Mateo-Git** [abekermsx/Final-Fantasy-MSX-Performance-Patch#3]
Hi, first off, I want to thank you devoted fans for your work on this patch and the fan translation.
As someone who played the game prior to this release I can say it truly improves the performance and loading times. And the fan translation is well done, using the NES version as a basis was a good idea/call. After all, inferior performance and loading times aside, it can be considered the definite 8-bit version of FFI thanks to the bug-fixes, better graphics and audio (those remixes are pretty great).

Regarding my question, as I said, I played this game in Japanese first and therefore wanted to try my save with the fan translation. As I expected, after inserting the user disk, the save loaded just fine but the names were all garbled. So, my question is, maybe during your work with the game you guys found the memory addresses of the playable characters names and the respective character table? or created any other tool to modify this? I'd like to modify my party's names in English and Japanese and that's why I'm asking.
I would really appreciate any help you can provide me, thank you.

**Comment by abekermsx** [comment]
Thanks :) I only created the performance patch, not the English translation, so I don't know everything about the naming of the players. Even so, it wasn't hard to find the locations of the names on the user disk.

If you use a hex-editor you'll find the names in the following locations:
0x01402h-0x01405h
0x01442h-0x01445h
0x01482h-0x01485h
0x014C2h-0x014C5h

The names aren't stored using ASCII encoding :(

The upper case characters use from hex-codes 0x08A (0x08A = A, 0x08B = B, ...).
The lower case characters use from hex-codes 0x0A4 (0x0A4 = a, 0x0A5 = b, ...).
Numbers use hex-codes from 0x080 (0x080 = 0, 0x081 =1, ...)

Hope this helps!

(edit) In fact, this file lists all the mappings from hex-codes to characters:
[https://github.com/romh-acking/final-fantasy-msx2-en/blob/master/asm/CHR%20-%20New.tbl]((https://github.com/romh-acking/final-fantasy-msx2-en/blob/master/asm/CHR%20-%20New.tbl))
(I'm not sure if the special characters work correctly)

**Comment by Mateo-Git** [comment]
Thank you!, that was really helpful, just what I needed.
I didn't expect that editing the User disk would be so straightforward, but luckily looks like Square didn't care about checksums back when they ported FFI to the MSX. I did exactly what you mentioned and was able to edit the names with the addresses and the character table you shared. Thanks again, cheers :)
